<?php

global $bpOptions;

// do not edit this file
// all values are set via config settings or upon use

$bpOptions['SSLcert'] = '';

$bpOptions['SSLkey'] = '';

$bpOptions['secret'] = '';

$bpOptions['notificationEmail'] = '';

$bpOptions['notificationURL'] = '';

$bpOptions['redirectURL'] = '';

$bpOptions['currency'] = '';

$bpOptions['physical'] = 'true';

$bpOptions['fullNotifications'] = 'true';

$bpOptions['transactionSpeed'] = 'low'; 

?>